### PR TITLE
Add Lykon

### PR DESCRIPTION
**Pull request by kieranajp**

### CODE REVIEW

**Comment by sarupbanskota** [comment]
Thanks @kieranajp. Mind sending in a [verification email please](https://github.com/codecrafters-io/learning-stipends#contribute)? I'll merge it after :)

**Comment by kieranajp** [comment]
Yep, already sent it yesterday :+1:

**Comment by sarupbanskota** [comment]
@kieranajp just making sure, did you email hello@codecrafters.io? don't seem to have received an email about Lykon yet 🤔

**Comment by kieranajp** [comment]
@sarupbanskota Apologies, it was stuck in drafts (was travelling and had flaky internet so I guess that's why).

Sent now.

**Comment by sarupbanskota** [comment]
Thanks!

**Pull request merged**
